import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ReactNode, useState } from "react";
import Footer from "@/components/Footer";
import HappyClients from "@/components/homePage/HappyClients";
import TrustedBy from "@/components/homePage/TrustedBy";
import OurCultureSection from "@/components/homePage/OurCultureSection";
import CertifiedSection from "@/components/homePage/CertifiedSection2";
import HeroSection from "@/components/homePage/HeroSection";
import { IPageName } from "@/types/indext";

const inter = Inter({ subsets: ["latin"] });

interface ISiteLayoutProps {
  children: ReactNode;
  pageName:
    | "BSL Home"
    | "Spectrum Fibre"
    | "Infra Services"
    | "Digital Payment"
    | "Business"
    | "About"
    | "Career";
}

export default function SiteLayout({ children, pageName }: ISiteLayoutProps) {
  return (
    <>
      <Head>
        <title>BSL Websites | {pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative text-white">
        <Navbar pageName={pageName} />
        {children}
        <Footer />
      </main>
    </>
  );
}
