import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ReactNode, useEffect, useRef, useState } from "react";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

import { Cursor } from "react-creative-cursor";
import "react-creative-cursor/dist/styles.css";

interface ISiteLayoutProps {
  children: ReactNode;
  pageName:
    | "BSL Home"
    | "Spectrum Fibre"
    | "Infra Services"
    | "Digital Payment"
    | "Business"
    | "About"
    | "Career"
    | "Enquiry"
    | "Galley";
}

export default function SiteLayout({ children, pageName }: ISiteLayoutProps) {
  const dropdownRef = useRef<HTMLDivElement>(null);

  // useEffect(() => {
  //   const handleOutsideClick = (event: MouseEvent) => {
  //     if (
  //       dropdownRef.current &&
  //       !dropdownRef.current.contains(event.target as Node)
  //     ) {
  //       // setIsOpen(false);
  //     }
  //   };

  //   window.addEventListener("mousedown", handleOutsideClick);

  //   return () => {
  //     window.removeEventListener("mousedown", handleOutsideClick);
  //   };
  // }, [dropdownRef]);

  return (
    <>
      <Head>
        <title>BSL Websites | {pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative text-white bg-[#000A26]" ref={dropdownRef}>
        <Cursor isGelly={true} cursorBackgrounColor="#C0392B" cursorSize={30} />
        <div className="cursor"></div>
        <Navbar pageName={pageName} />
        {children}
        <Footer />
      </main>
    </>
  );
}
